# Generated by Django 3.2.2 on 2021-05-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fixtures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t1', models.CharField(max_length=100)),
                ('t2', models.CharField(max_length=100)),
                ('t1g', models.IntegerField(blank=True)),
                ('t2g', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('mp', models.IntegerField(default=0)),
                ('w', models.IntegerField(default=0)),
                ('d', models.IntegerField(default=0)),
                ('l', models.IntegerField(default=0)),
                ('gf', models.IntegerField(default=0)),
                ('ga', models.IntegerField(default=0)),
                ('gd', models.IntegerField(default=0)),
                ('pts', models.IntegerField(default=0)),
            ],
        ),
    ]
