# Generated by Django 3.2.2 on 2021-05-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addteam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixtures',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fixtures',
            name='t1g',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fixtures',
            name='t2g',
            field=models.IntegerField(default=0),
        ),
    ]
